### ISSUE TITLE
Interactive plots

### ISSUE THREAD

**Issue by mofeing** [bsc-quantic/OptimizedEinsum.jl#10]
Makie (and GraphMakie) allow registering interactive callbacks to plots such that nodes or edges are highlighted, a popup with more info gets displayed, ...

For this you need an interactive backend (i.e. GLMakie or WGLMakie).

I have been unsuccessful.

**Comment by jofrevalles** [comment]
I have been testing the possibility to display the path labels when hovering the edges with the mouse. The interaction can be disabled with the keyword argument `interaction=false` in both `plot` and `plot!` functions. 

### Example
```julia
julia> using OptimizedEinsum
julia> using Makie
julia> using GLMakie
julia> output, inputs, size_dict = rand_equation(20, 5)
(Symbol[], [[:k, :g, :W, :c, :M], [:D, :u, :f], [:K, :j, :A, :q, :e, :w, :P], [:h, :G, :l, :M], [:S, :Q, :V, :O], [:m, :G, :E, :k, :y], [:u, :T, :x, :O, :s, :l, :t], [:z, :I, :i, :C], [:B, :h, :n], [:U, :t, :f, :R, :L], [:E, :y, :s, :a, :I, :d, :T, :x, :N, :U], [:F, :S, :d, :c, :D, :b, :R], [:r, :n, :J, :C, :i, :m], [:L, :g], [:P, :v, :r, :o, :e], [:H, :o], [:j, :v, :q, :p], [:V, :H, :w, :B, :K], [:Q, :X, :F, :J, :A], [:z, :b, :p, :W, :X, :a, :N]], Dict(:j => 7, :D => 7, :S => 3, :X => 8, :x => 2, :R => 9, :A => 6, :d => 3, :k => 7, :g => 2…))
julia> path = contractpath(RandomGreedy, inputs, output, size_dict)
ContractionPath([(17, 3), (10, 14), (21, 15), (23, 16), (22, 2), (24, 18), (13, 9), (1, 4), (27, 8), (28, 6), (26, 5), (25, 7), (31, 19), (33, 29), (34, 20), (32, 11), (35, 12), (37, 36), (30, 38)], [[:k, :g, :W, :c, :M], [:D, :u, :f], [:K, :j, :A, :q, :e, :w, :P], [:h, :G, :l, :M], [:S, :Q, :V, :O], [:m, :G, :E, :k, :y], [:u, :T, :x, :O, :s, :l, :t], [:z, :I, :i, :C], [:B, :h, :n], [:U, :t, :f, :R, :L], [:E, :y, :s, :a, :I, :d, :T, :x, :N, :U], [:F, :S, :d, :c, :D, :b, :R], [:r, :n, :J, :C, :i, :m], [:L, :g], [:P, :v, :r, :o, :e], [:H, :o], [:j, :v, :q, :p], [:V, :H, :w, :B, :K], [:Q, :X, :F, :J, :A], [:z, :b, :p, :W, :X, :a, :N]], Symbol[], Dict(:j => 7, :D => 7, :S => 3, :X => 8, :x => 2, :R => 9, :A => 6, :d => 3, :k => 7, :g => 2…))
julia> plot(path; interaction=true)
(Scene (800px, 600px):
  0 Plots
  3 Child Scenes:
    ├ Scene (800px, 600px)
    ├ Scene (800px, 600px)
    └ Scene (800px, 600px), Axis (1 plots), Combined{GraphMakie.graphplot, Tuple{Graphs.SimpleGraphs.SimpleDiGraph{Int64}}})
```
![image](https://user-images.githubusercontent.com/61060572/219701855-3020dc5b-8f42-4974-8796-05940b5dc1ee.png)

### Problems
Currently, the behavior of the interaction is not optimal, the labels appear with lag, and there is no way to tune the sensitivity of the mouse interaction. Maybe we could plot the labels all at once instead of by mouse interaction, since now it is difficult to understand.

What do you think, @mofeing ?

**Comment by mofeing** [comment]
I like the idea of showing all labels but it should be optional. Something like a `labels` keyword argument.

About the interaction, I don't understand what you mean about "sensitivity of the mouse interaction". Maybe you can show me next week.
